/*
SQLyog Community v12.5.1 (64 bit)
MySQL - 10.1.30-MariaDB : Database - baeportal
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`baeportal` /*!40100 DEFAULT CHARACTER SET utf8 */;

USE `baeportal`;

/*Table structure for table `tm_profile` */

DROP TABLE IF EXISTS `tm_profile`;

CREATE TABLE `tm_profile` (
  `PROFILE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_ID` int(11) NOT NULL,
  `PROFILE_NPWP` varchar(15) DEFAULT NULL,
  `PROFILE_COMPANY_NAME` varchar(200) DEFAULT NULL,
  `PROFILE_BUILDING` varchar(100) DEFAULT NULL,
  `PROFILE_ADDRESS` text,
  `PROFILE_COUNTRY` int(11) DEFAULT NULL,
  `PROFILE_STATE` int(11) DEFAULT NULL,
  `PROFILE_CITY` int(11) DEFAULT NULL,
  `PROFILE_POST_CODE` varchar(10) DEFAULT NULL,
  `PROFILE_WEBSITE` varchar(100) DEFAULT NULL,
  `PROFILE_EMAIL` varchar(100) DEFAULT NULL,
  `PROFILE_PHONE` varchar(50) DEFAULT NULL,
  `PROFILE_FAX` varchar(50) DEFAULT NULL,
  `PROFILE_PIC` varchar(100) DEFAULT NULL,
  `PROFILE_PIC_EMAIL` varchar(100) DEFAULT NULL,
  `PROFILE_PIC_PHONE` varchar(50) DEFAULT NULL,
  `PROFILE_PIC_MOBILE` varchar(50) DEFAULT NULL,
  `CREATED_BY` int(11) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`PROFILE_ID`),
  KEY `fk_TX_PROFILE_TM_USERS_idx` (`USER_ID`),
  CONSTRAINT `fk_TX_PROFILE_TM_USERS` FOREIGN KEY (`USER_ID`) REFERENCES `tm_users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tm_profile` */

/*Table structure for table `tm_users` */

DROP TABLE IF EXISTS `tm_users`;

CREATE TABLE `tm_users` (
  `USER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_EMAIL` varchar(100) NOT NULL,
  `USER_PASSWORD` varchar(100) NOT NULL,
  `USER_NAME` varchar(100) DEFAULT NULL,
  `USER_ROLE_ID` int(11) NOT NULL,
  `USER_STATUS_ID` int(11) NOT NULL,
  `USER_LAST_LOGIN` datetime DEFAULT NULL,
  `SESSION_ID` varchar(100) DEFAULT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`USER_ID`),
  KEY `fk_TM_USERS_TR_ROLE1_idx` (`USER_ROLE_ID`),
  KEY `fk_TM_USERS_TR_USER_STATUS1_idx` (`USER_STATUS_ID`),
  CONSTRAINT `fk_TM_USERS_TR_ROLE1` FOREIGN KEY (`USER_ROLE_ID`) REFERENCES `tr_role` (`ROLE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TM_USERS_TR_USER_STATUS1` FOREIGN KEY (`USER_STATUS_ID`) REFERENCES `tr_user_status` (`USER_STATUS_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tm_users` */

/*Table structure for table `tr_article_type` */

DROP TABLE IF EXISTS `tr_article_type`;

CREATE TABLE `tr_article_type` (
  `ARTICLE_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ARTICLE_TYP_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ARTICLE_TYPE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;

/*Data for the table `tr_article_type` */

insert  into `tr_article_type`(`ARTICLE_TYPE_ID`,`ARTICLE_TYP_NAME`) values 
(1,'BERITA'),
(2,'KEGIATAN PASAR MODAL'),
(3,'PERATURAN'),
(4,'TATA CARA CA'),
(5,'COMPANY PROFILE');

/*Table structure for table `tr_ca_type` */

DROP TABLE IF EXISTS `tr_ca_type`;

CREATE TABLE `tr_ca_type` (
  `CA_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CA_TYPE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`CA_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tr_ca_type` */

/*Table structure for table `tr_report_type` */

DROP TABLE IF EXISTS `tr_report_type`;

CREATE TABLE `tr_report_type` (
  `REPORT_TYPE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPORT_TYPE_NAME` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`REPORT_TYPE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tr_report_type` */

/*Table structure for table `tr_role` */

DROP TABLE IF EXISTS `tr_role`;

CREATE TABLE `tr_role` (
  `ROLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ROLE_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`ROLE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tr_role` */

/*Table structure for table `tr_user_status` */

DROP TABLE IF EXISTS `tr_user_status`;

CREATE TABLE `tr_user_status` (
  `USER_STATUS_ID` int(11) NOT NULL AUTO_INCREMENT,
  `USER_STATUS_NAME` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`USER_STATUS_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tr_user_status` */

/*Table structure for table `tx_article` */

DROP TABLE IF EXISTS `tx_article`;

CREATE TABLE `tx_article` (
  `ARTICLE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `ARTICLE_USER_ID` int(11) NOT NULL,
  `ARTICLE_TYPE_ID` int(11) NOT NULL,
  `ARTICLE_TITTLE` varchar(200) DEFAULT NULL,
  `ARTICLE_PROLOG` varchar(255) DEFAULT NULL,
  `ARTICLE_TEXT` longtext,
  `ARTICLE_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `ARTICLE_STATUS` int(11) DEFAULT NULL,
  `ARTICLE_HIGHLIGHT` int(11) DEFAULT '0',
  `ARTICLE_READ` int(11) DEFAULT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ARTICLE_ID`),
  KEY `fk_TX_ARTICLE_TM_USERS1_idx` (`ARTICLE_USER_ID`),
  KEY `fk_TX_ARTICLE_TR_ARTICLE_TYPE1_idx` (`ARTICLE_TYPE_ID`),
  CONSTRAINT `fk_TX_ARTICLE_TM_USERS1` FOREIGN KEY (`ARTICLE_USER_ID`) REFERENCES `tm_users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TX_ARTICLE_TR_ARTICLE_TYPE1` FOREIGN KEY (`ARTICLE_TYPE_ID`) REFERENCES `tr_article_type` (`ARTICLE_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tx_article` */

/*Table structure for table `tx_ca` */

DROP TABLE IF EXISTS `tx_ca`;

CREATE TABLE `tx_ca` (
  `CA_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CA_TYPE_ID` int(11) NOT NULL,
  `PROFILE_ID` int(11) NOT NULL,
  `CA_DATE` date DEFAULT NULL,
  `CA_PATH` varchar(200) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CA_ID`),
  KEY `fk_TX_CA_TR_CA_TYPE1_idx` (`CA_TYPE_ID`),
  KEY `fk_TX_CA_TX_PROFILE1_idx` (`PROFILE_ID`),
  KEY `fk_TX_CA_TM_USERS1_idx` (`CREATED_BY`),
  CONSTRAINT `fk_TX_CA_TM_USERS1` FOREIGN KEY (`CREATED_BY`) REFERENCES `tm_users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TX_CA_TR_CA_TYPE1` FOREIGN KEY (`CA_TYPE_ID`) REFERENCES `tr_ca_type` (`CA_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TX_CA_TX_PROFILE1` FOREIGN KEY (`PROFILE_ID`) REFERENCES `tm_profile` (`PROFILE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tx_ca` */

/*Table structure for table `tx_contact_us` */

DROP TABLE IF EXISTS `tx_contact_us`;

CREATE TABLE `tx_contact_us` (
  `CONTACT_US_ID` int(11) NOT NULL AUTO_INCREMENT,
  `CONTACT_US_EMAIL` varchar(100) DEFAULT NULL,
  `CONTACT_US_TITTLE` varchar(200) DEFAULT NULL,
  `CONTACT_US_TEXT` text,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`CONTACT_US_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tx_contact_us` */

/*Table structure for table `tx_report` */

DROP TABLE IF EXISTS `tx_report`;

CREATE TABLE `tx_report` (
  `REPORT_ID` int(11) NOT NULL AUTO_INCREMENT,
  `REPORT_TYPE_ID` int(11) NOT NULL,
  `PROFILE_ID` int(11) NOT NULL,
  `REPORT_DATE` date DEFAULT NULL,
  `REPORT_PATH` varchar(200) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`REPORT_ID`),
  KEY `fk_TX_REPORT_TR_REPORT_TYPE1_idx` (`REPORT_TYPE_ID`),
  KEY `fk_TX_REPORT_TX_PROFILE1_idx` (`PROFILE_ID`),
  KEY `fk_TX_REPORT_TM_USERS1_idx` (`CREATED_BY`),
  CONSTRAINT `fk_TX_REPORT_TM_USERS1` FOREIGN KEY (`CREATED_BY`) REFERENCES `tm_users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TX_REPORT_TR_REPORT_TYPE1` FOREIGN KEY (`REPORT_TYPE_ID`) REFERENCES `tr_report_type` (`REPORT_TYPE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_TX_REPORT_TX_PROFILE1` FOREIGN KEY (`PROFILE_ID`) REFERENCES `tm_profile` (`PROFILE_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tx_report` */

/*Table structure for table `tx_slider` */

DROP TABLE IF EXISTS `tx_slider`;

CREATE TABLE `tx_slider` (
  `SLIDER_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SLIDER_NAME` varchar(100) DEFAULT NULL,
  `SLIDER_PATH` varchar(200) DEFAULT NULL,
  `SLIDER_DISPLAY` char(1) DEFAULT NULL,
  `SLIDER_SORT` int(11) DEFAULT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_AT` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`SLIDER_ID`),
  KEY `fk_TX_SLIDER_TM_USERS1_idx` (`CREATED_BY`),
  CONSTRAINT `fk_TX_SLIDER_TM_USERS1` FOREIGN KEY (`CREATED_BY`) REFERENCES `tm_users` (`USER_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Data for the table `tx_slider` */

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
